export const items = [
  {
    id: 1,
    title: "Bread - Sticks, Thin, Plain",
    price: 13132,
    desc: "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    img: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
  },
  {
    id: 2,
    title: "Tea - Lemon Scented",
    price: 27635,
    desc: "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    img: "http://dummyimage.com/300x300.png/cc0000/ffffff",
  },
  {
    id: 3,
    title: "Bag Clear 10 Lb",
    price: 37261,
    desc: "Fusce consequat. Nulla nisl. Nunc nisl.",
    img: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
  },
  {
    id: 4,
    title: "Soup - Campbells, Beef Barley",
    price: 44774,
    desc: "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    img: "http://dummyimage.com/300x300.png/dddddd/000000",
  },
  {
    id: 5,
    title: "Cookie Double Choco",
    price: 43434,
    desc: "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    img: "http://dummyimage.com/300x300.png/ff4444/ffffff",
  },
  {
    id: 6,
    title: "Eggwhite Frozen",
    price: 32970,
    desc: "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    img: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
  },
  {
    id: 7,
    title: "Pastry - Banana Tea Loaf",
    price: 40960,
    desc: "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    img: "http://dummyimage.com/300x300.png/ff4444/ffffff",
  },
  {
    id: 8,
    title: "Compound - Pear",
    price: 16817,
    desc: "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    img: "http://dummyimage.com/300x300.png/cc0000/ffffff",
  },
  {
    id: 9,
    title: "Yeast Dry - Fermipan",
    price: 46080,
    desc: "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    img: "http://dummyimage.com/300x300.png/dddddd/000000",
  },
  {
    id: 10,
    title: "Egg - Salad Premix",
    price: 17671,
    desc: "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    img: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
  },
  {
    id: 11,
    title: "Sansho Powder",
    price: 44723,
    desc: "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    img: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
  },
  {
    id: 12,
    title: "Rye Special Old",
    price: 17925,
    desc: "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    img: "http://dummyimage.com/300x300.png/dddddd/000000",
  },
  {
    id: 13,
    title: "Dried Cranberries",
    price: 43828,
    desc: "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    img: "http://dummyimage.com/300x300.png/ff4444/ffffff",
  },
  {
    id: 14,
    title: "Sugar - Splenda Sweetener",
    price: 43349,
    desc: "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    img: "http://dummyimage.com/300x300.png/ff4444/ffffff",
  },
  {
    id: 15,
    title: "Truffle Cups - White Paper",
    price: 23960,
    desc: "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    img: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
  },
  {
    id: 16,
    title: "Mint - Fresh",
    price: 43431,
    desc: "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    img: "http://dummyimage.com/300x300.png/dddddd/000000",
  },
  {
    id: 17,
    title: "Chicken - Breast, 5 - 7 Oz",
    price: 14678,
    desc: "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    img: "http://dummyimage.com/300x300.png/cc0000/ffffff",
  },
  {
    id: 18,
    title: "Quinoa",
    price: 15402,
    desc: "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    img: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
  },
  {
    id: 19,
    title: "Wine - Red, Pelee Island Merlot",
    price: 31920,
    desc: "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    img: "http://dummyimage.com/300x300.png/dddddd/000000",
  },
  {
    id: 20,
    title: "Berry Brulee",
    price: 12311,
    desc: "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    img: "http://dummyimage.com/300x300.png/5fa2dd/ffffff",
  },
];
